# Generated by Django 5.0.6 on 2024-05-29 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_controller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_priority', models.CharField(choices=[('A', 'All'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='A', max_length=1)),
                ('task_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_priority_tbl',
                'unique_together': {('task_priority', 'task_user')},
            },
        ),
    ]
